## Indexing and Silicing ###

In [3]:
import numpy as np

In [7]:
arr = np.arange(10);
print("Basic Silicing : ",arr[2:7])
print("With Step",arr[2:7:2])
print("Negative Indexing : ",arr[-3])

Basic Silicing :  [2 3 4 5 6]
With Step [2 4 6]
Negative Indexing :  7


## 2D Array Silicing

In [17]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

print("Specific Element : ",arr_2d[1,2])
print("Whole Row : ",arr_2d[1])
print("Whole Column : ",arr_2d[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element :  6
Whole Row :  [4 5 6]
Whole Column :  [3 6 9]


# Sorting

In [18]:
unsorted = np.array([3,1,4,6,5,8,2,10])
print("Sorted Array : ",np.sort(unsorted))

Sorted Array :  [ 1  2  3  4  5  6  8 10]


In [24]:
arr_2d = np.array([[3,1],[1,2],[2,3]])
print(arr_2d)

print("2D Sorted Array By Column : ",np.sort(arr_2d,axis=0))
print("2D Sorted Array By Row : ",np.sort(arr_2d,axis=1))

[[3 1]
 [1 2]
 [2 3]]
2D Sorted Array By Column :  [[1 1]
 [2 2]
 [3 3]]
2D Sorted Array By Row :  [[1 3]
 [1 2]
 [2 3]]


# Filtering

In [25]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print("Even Numbers : ",numbers[numbers%2==0])

Even Numbers :  [ 2  4  6  8 10]


#  Filter with mask

In [28]:
mask = numbers%2==0
print("Mask : ",mask)
print("Even Numbers Using Mask : ",numbers[mask])

Mask :  [False  True False  True False  True False  True False  True]
Even Numbers Using Mask :  [ 2  4  6  8 10]


## Fancing  Indexing  vs np.wjhere()

In [33]:
indices = [1,3,5,7]
print("Elements at Specific Indices : ",numbers[indices])

# numbers  --- IGNORE ---
where_even = np.where(numbers>5)
print("Indices of Even Numbers : ",numbers[where_even])

Elements at Specific Indices :  [2 4 6 8]
Indices of Even Numbers :  [ 6  7  8  9 10]


# Conditions 

In [40]:
conditions = np.where(numbers>5,numbers*2,numbers)
print("Conditions : ",conditions)

Conditions :  [ 1  2  3  4  5 12 14 16 18 20]


# Adding and removing Data

In [43]:
arr = np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("Concatenated Array : ",np.concatenate((arr,arr2)))


Concatenated Array :  [ 1  2  3  4  5  6  7  8  9 10]


###  Array Compatibility  ###

In [50]:
a = np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])
print("Compatibilty shape : ",a.shape==b.shape)


Compatibilty shape :  True


# Compatibility shape :  False

In [58]:
original = np.array([[1,2],[3,4]])
print("Original Array : ",original)
new_row = np.array([[5,6]])
print("Array after Adding Row : ",np.vstack((original,new_row)))
new_col = np.array([[7],[8],[9]])
original_expanded = np.vstack((original, new_row))
print("Array after Adding Column : ",np.hstack((original_expanded,new_col)))

Original Array :  [[1 2]
 [3 4]]
Array after Adding Row :  [[1 2]
 [3 4]
 [5 6]]
Array after Adding Column :  [[1 2 7]
 [3 4 8]
 [5 6 9]]


### Delete Element

In [59]:
arr = np.array([1,2,3,4,5])
deleted_element = np.delete(arr,2)
print("Array after Deleting Element at Index 2 : ",deleted_element)

Array after Deleting Element at Index 2 :  [1 2 4 5]
