## NumPy array and basics

In [2]:
import numpy as np 

In [4]:
arr_1d = np.array([1,2,3,4,5]);
print("arr1 : ",arr_1d*2)

arr1 :  [ 2  4  6  8 10]


In [8]:
arr_1d = [1,2,3,4,5]
print("arr1 : ",arr_1d*2)

import time
start = time.time()
py_list =[i*2 for i in range(1000000)]
print("\n List operation time :",time.time()-start)

start = time.time()
arr_1d = np.arange(100000)*2
print("\n Numpy operation time :",time.time()-start)



arr1 :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

 List operation time : 0.3616664409637451

 Numpy operation time : 0.0014834403991699219


In [10]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
full = np.full((2,2),7)
print(full)

random =np.random.random((2,3))
print(random)


[[7 7]
 [7 7]]
[[0.55113527 0.05130381 0.4003309 ]
 [0.31535079 0.51955772 0.41199731]]


In [14]:
sequence = np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


In [15]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [16]:
tensor = np.array([[[1,2],[3,4]],[[3,4],[1,4]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[3 4]
  [1 4]]]


## Array Properties

In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


## Array Reshaping


In [24]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3,4)
print(reshaped)

transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
