In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.random.rand(4,4)
array3 = np.zeros((4,4))

array1 = np.array([1, 2, 3, 4, 5])     
array2 = np.random.rand(4)        
array3 = np.zeros((4,4))               

print("Array 1:\n", array1)
print("\nArray 2 (Random):\n", array2)
print("\nArray 3 (Zeros 4x4):\n", array3)
 

Array 1:
 [1 2 3 4 5]

Array 2 (Random):
 [0.8724846  0.69800205 0.67808788 0.46580998]

Array 3 (Zeros 4x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
np.save('array1.npy', array1)

In [4]:
loaded_array = np.load('array1.npy')
print(loaded_array)

[1 2 3 4 5]
